# Generated by Django 3.2.8 on 2021-10-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_name', models.CharField(max_length=64)),
                ('lot_price', models.IntegerField()),
                ('lot_description', models.CharField(max_length=128)),
                ('lot_date', models.DateTimeField(auto_now=True)),
                ('lot_status', models.BooleanField()),
                ('lot_author', models.CharField(max_length=64)),
                ('lot_category', models.CharField(max_length=64)),
            ],
        ),
    ]
