# Generated by Django 3.2.8 on 2021-10-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_lot'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleimage', models.CharField(max_length=64)),
                ('lot_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
