# Generated by Django 3.2.8 on 2021-10-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_lot_lot_viewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_viewimage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagelot', to='auctions.lotimage'),
        ),
    ]
