# Generated by Django 3.2.8 on 2021-10-30 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_lot_lot_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
