# Generated by Django 3.2.8 on 2021-10-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_lotcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.lotcategory'),
        ),
    ]
