# Generated by Django 3.2.9 on 2021-11-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_lot_lot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_description',
            field=models.CharField(max_length=256),
        ),
    ]
