# Generated by Django 3.2.9 on 2021-11-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_lot_lot_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='lot_bid',
        ),
    ]
